### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by hodanli** [WorldBrain/memex-local-sync#8]
i get this error when i try to run memex-desktop 0.0.7. i am using win 11. i uninstalled all previous versions and tried clean install but did not help.

![image](https://github.com/WorldBrain/memex-desktop/assets/6535865/51e8589b-28b7-4096-9677-0e8423e6ee76)

**Comment by blackforestboi** [comment]
Thanks for the note, we're investigating!

**Comment by changhiskhan** [comment]
we just released v0.3.10 yesterday but I think there was an issue publishing to NPM where all other platforms got published to NPM but windows did not (https://www.npmjs.com/package/vectordb?activeTab=dependencies). We're going to get that up there today. Thanks for the bug report and patience!

**Comment by blackforestboi** [comment]
Thanks @changhiskhan for chiming in!

@hodanli: Check out the latest 0.0.9 release of Memex Desktop and see if it works now - updated the affected package of Lance

**Comment by hodanli** [comment]
unfortunately. i get the same error using: Memex-Desktop-v0.0.9-win-x64.

![image](https://github.com/WorldBrain/memex-desktop/assets/6535865/d0f85e5c-824f-4689-ab96-e6a966fb2e63)

**Comment by changhiskhan** [comment]
curious what electron is actually looking for. Here's the actual artifact on npmjs: https://www.npmjs.com/package/@lancedb/vectordb-win32-x64-msvc, you can see that the latest version is up there.

**Comment by hodanli** [comment]
[0.0.23](https://github.com/WorldBrain/memex-desktop/releases/tag/v0.0.23)

this works without issue.

**Comment by blackforestboi** [comment]
Thanks for the feedback!
